package Calibrate::RootCount;

use strict;
use warnings;

use base 'Exporter';
our @EXPORT_OK = qw(root_count);

# ---------------------------------------------------------------------
# Exact count of g'th roots of a value a modulo qq, GIVEN that a
# solution exists - i.e. the size of res_array()->count that
# alloc_square()/allrootmod() would compute, without needing to run
# allrootmod() at all: just from (g, factorization of qq).
#
# This is the missing piece flagged in calibration-estimator-status.md
# ("r_walk (g'th-root walk size times res_array()->count) ... NOT
# implemented") and directly answers walk-cost-model-intro.md's request
# to look at the literature on counting g'th roots.
#
# THE MATH (standard, classical - e.g. Ireland & Rosen "A Classical
# Introduction to Modern Number Theory", or any elementary number
# theory text's treatment of primitive roots / cyclic group structure):
#
#   - For an odd prime p and a coprime to p, (Z/p^e Z)* is CYCLIC of
#     order phi(p^e) = p^(e-1)(p-1). In a cyclic group of order m, the
#     map x -> x^g has kernel of size gcd(g, m) - so x^g = a has either
#     0 solutions, or EXACTLY gcd(g, m) solutions, and (this is the
#     useful part) that count is the SAME for every solvable a, not
#     just an average.
#   - For p = 2: (Z/2^e Z)* is cyclic only for e <= 2; for e >= 3 it is
#     Z/2 x Z/2^(e-2) (generated by -1 and 5). The kernel of x -> x^g
#     on a direct product of cyclic groups C_n1 x C_n2 has size
#     gcd(g,n1)*gcd(g,n2), giving:
#       e = 1:            count = 1            (group is trivial)
#       e = 2:            count = gcd(g, 2)
#       e >= 3:           count = gcd(g, 2) * gcd(g, 2^(e-2))
#   - For composite qq: roots combine via CRT, so the total count is
#     the PRODUCT of the per-prime-power counts.
#
# Since alloc_square() already rejects the allocation outright when
# res_array()->count == 0 (coul.c: "if (rp->count == 0) return 0;"),
# any square that walk_v() actually gets to walk is KNOWN solvable by
# the time we'd call this - so the product-of-per-prime-counts formula
# is EXACT for that case, not an expectation over solvable/unsolvable.
# It says nothing about the PROBABILITY a given square is solvable at
# all (that depends on the specific residue value mod each prime power
# factor, not just on g and qq's factorization) - only recursion
# itself (via a real allrootmod() call) can determine that. This
# function answers "how many roots, given solvable", not "is it
# solvable".
#
# VALIDATED (this session) against real alloc_square()/res_array()
# output (a temporary "alloc_square vi=... g=... qq=... count=..."
# VERBOSE print added to coul.c) across every non-zero-count sample
# encountered on D(12,9) and D(204,8):
#   g=2  qq=6                (2*3)        -> predicted 2,   real 2
#   g=2  qq=4374             (2*3^7)      -> predicted 2,   real 2
#   g=2  qq=86093442         (2*3^16)     -> predicted 2,   real 2
#   g=2  qq=8, 32, 256, 512, 131072  (2^e, e=3..17) -> predicted 4, real 4
#   g=2  qq=4                (2^2)        -> predicted 2,   real 2
#   g=2  qq=2                (2^1)        -> predicted 1,   real 1
#   g=2  qq=196608           (2^16*3)     -> predicted 8,   real 8
#   g=2  qq=5898240          (2^17*3^2*5) -> predicted 16,  real 16
# All exact matches, no exceptions, across every qq structure sampled
# (pure powers of 2 at many exponents, and several mixed 2*3^k and
# 2^a*3^b*5 forms). g=16 samples encountered were all unsolvable
# (count=0) in this session's sampling - consistent with the formula
# (which allows 0), but not an independent confirmation of the g=16
# nonzero case specifically. The underlying theorem is generic in g
# (the same cyclic/direct-product kernel-size argument, not something
# specific to g=2), so this isn't considered a live gap, but a real
# g>2 nonzero example would still be worth checking if one turns up.
# ---------------------------------------------------------------------

sub _local_count {
    my($g, $p, $e) = @_;
    if ($p == 2) {
        return 1 if $e == 1;
        return _gcd($g, 2) if $e == 2;
        return _gcd($g, 2) * _gcd($g, 2 ** ($e - 2));
    }
    my $phi = $p ** ($e - 1) * ($p - 1);
    return _gcd($g, $phi);
}

sub _gcd {
    my($a, $b) = @_;
    ($a, $b) = ($b, $a % $b) while $b;
    return $a;
}

# ---------------------------------------------------------------------
# root_count($g, $qq): exact number of g'th roots of a (any solvable
# residue) modulo $qq. $qq may be passed as an integer or as a
# hashref of {prime => exponent} if the factorization is already
# known (as it should be here - qq = aq/q[vi], built from primes
# recursion has already forced, so factoring it from scratch is
# avoidable work in the real caller).
sub root_count {
    my($g, $qq) = @_;
    my %f;
    if (ref $qq eq 'HASH') {
        %f = %$qq;
    } else {
        my $n = $qq;
        my $d = 2;
        while ($d * $d <= $n) {
            while ($n % $d == 0) { $f{$d}++; $n /= $d; }
            $d++;
        }
        $f{$n}++ if $n > 1;
    }
    my $total = 1;
    $total *= _local_count($g, $_, $f{$_}) for keys %f;
    return $total;
}

1;
